# 1. Numpy
### 실제 분석에서는 통계자료를 분석한 후에 고급분석으로 넘어가는데, 대부분의 자료는 정규분포를 따르지 않는다. 하지만 우리가 관심 있는 건 통계량의 분포이고, 자료가 충분히 모이면 중심극한정리에 의해 통계량의 정규분포가 대부분 성립하므로 분석이 가능하다. 여기서 numpy가 쓰인다. 

In [3]:
import numpy as np #분포별 난수발생 가능


In [14]:
data=np.random.randn(2,2) #randn: 표준정규분포에서 샘플 생성 randn(행,열)
data, data.dtype, data.shape

(array([[ 2.28714804,  0.24122272],
        [-1.013013  , -1.55885841]]), dtype('float64'), (2, 2))

In [13]:
??np.random.randn #randn: 표준정규분포에서 샘플 생성 randn(행,열)

In [12]:
ls1=[1,2,3,4,5]
ls2=[6,7,8,9,10]
data1=np.array(ls1) # 벡터
data2=np.array([ls1,ls2]) # 행렬(2,5)
print(data2,data2.dtype,data2.shape,data2.ndim)
data3=np.asarray(ls1) # 새로운 객체 생상
data4=np.asarray(data1) # 기존의 darray 공유, 즉 data1과 4는 같은 주소를 같는다. 
print(id(data1),id(data4),id(data3))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] int32 (2, 5) 2
1743392419968 1743392419968 1743392550960


In [44]:
print("결과값: {0}".format(np.arange(4,13,4)))
print("결과값: {0}".format(np.zeros(4)))
print("결과값: \n{0}".format(np.zeros((4,4)))) # 행렬을 인자로 하려면 (행,열) 꼴로 대입. 즉 ()를 기입해야 함.
print("결과값: {0}".format(np.zeros_like(ls1)))
print("결과값: {0}".format(np.zeros_like(data1)))
print("결과값: \n{0}".format(np.eye(4)))
print("결과값: \n{0}".format(np.empty((3,3))))





결과값: [ 4  8 12]
결과값: [0. 0. 0. 0.]
결과값: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
결과값: [0 0 0 0 0]
결과값: [0 0 0 0 0]
결과값: 
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
결과값: 
[[0.00000000e+000 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 0.00000000e+000 5.86949987e-321]
 [1.56603289e-311 0.00000000e+000 1.56775183e-311]]


In [47]:
data1-1

array([0, 1, 2, 3, 4])

In [50]:
print(data1[0:3:2],data1[1:3])

[1 3] [2 3]


In [62]:
x=data1[0:3]
y=data1[0:3].copy()
print(x,y)
data1[2]=100
print(x,y) #copy 안하면 data1을 공유하므로 data1에 변형이 오면 x에도 변형이 온다 

[1 2 3] [1 2 3]
[  1   2 100] [1 2 3]


In [127]:
Y=np.array([5,6,7],dtype=np.string_)
print(Y)
Y= Y.astype(np.complex64)
print(Y.dtype)

[b'5' b'6' b'7']
complex64


In [81]:
A=np.array([[2,4,6,8],[1,3,5,7],[0,6,9,10]])
print(A,A[2][2],A[2,2],
      A[:2,1:3])

[[ 2  4  6  8]
 [ 1  3  5  7]
 [ 0  6  9 10]] 9 9 [[4 6]
 [3 5]]


In [133]:
a3=np.array([[[2,4,6,8],[1,3,5,7],[0,6,9,10]],
           [[11,12,13,14],[15,16,17,18],[19,20,21,22]]])
print("{0}\n\n{1}".format(a3,a3[:2,0:2,0:3])) # nd객체[차원범위,행범위,열범위] 혹은 nd객체[차원범위][차원범위,행범위,열범위]
print(a3[1,1,1]) # nd객체[차원,행,열]
print(a3[:2,1,:2])

[[[ 2  4  6  8]
  [ 1  3  5  7]
  [ 0  6  9 10]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]

[[[ 2  4  6]
  [ 1  3  5]]

 [[11 12 13]
  [15 16 17]]]
16
[[ 1  3]
 [15 16]]


In [114]:
a3_bool=a3==3
print(a3_bool)
a3[a3_bool]

[[[False False False False]
  [False  True False False]
  [False False False False]]

 [[False False False False]
  [False False False False]
  [False False False False]]]


array([3])

In [113]:
sex=np.array(["m","m","f","f"])
score=np.array([[90,80,50,20],[49,29,48,88],[68,39,99,16],[78,90,84,44]])
cl=score[sex=="m"]
cl

array([[90, 80, 50, 20],
       [49, 29, 48, 88]])

In [135]:
grade=np.array([["a","a","b"],["b","c","c"]])
a3[(a3>=19) |(a3<=5)]


array([ 2,  4,  1,  3,  5,  0, 19, 20, 21, 22])

In [168]:
fc=np.random.randn(7,4)
fc1=fc[[5,2,1]]
fc2=fc[[-2,-1,-4]]
print("{0}\n\n{1}\n\n{2}\n\n{3}\n\n{4}".format(fc,fc1,fc2,fc[[1,2,3],[1,2,3]],fc[[1,2,4]][:,[1,2,3]]))

[[-1.34667262  0.64133922 -0.78003462 -0.66677917]
 [ 0.15913369 -0.12685381  2.28960613  0.14078566]
 [ 0.9541955   0.8028677   0.15380564  0.56045416]
 [-0.92706522  0.17500056  0.60931629 -0.98989329]
 [-0.43288459  0.27539035  0.17205437 -0.31700179]
 [-0.29778978 -2.23591581 -0.88771874 -0.47046897]
 [ 0.84256354 -1.24682118  0.89293347 -0.44379443]]

[[-0.29778978 -2.23591581 -0.88771874 -0.47046897]
 [ 0.9541955   0.8028677   0.15380564  0.56045416]
 [ 0.15913369 -0.12685381  2.28960613  0.14078566]]

[[-0.29778978 -2.23591581 -0.88771874 -0.47046897]
 [ 0.84256354 -1.24682118  0.89293347 -0.44379443]
 [-0.92706522  0.17500056  0.60931629 -0.98989329]]

[-0.12685381  0.15380564 -0.98989329]

[[-0.12685381  2.28960613  0.14078566]
 [ 0.8028677   0.15380564  0.56045416]
 [ 0.27539035  0.17205437 -0.31700179]]


In [144]:
n=np.arange(25).reshape(5,5)
nt=n.T
print(n)
print(nt)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [185]:
at=a3.transpose(2,0,1)
at1=a3.transpose(0,1,2)
print(a3)
print(at)
print(at1)

[[[ 2  4  6  8]
  [ 1  3  5  7]
  [ 0  6  9 10]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]
[[[ 2  1  0]
  [11 15 19]]

 [[ 4  3  6]
  [12 16 20]]

 [[ 6  5  9]
  [13 17 21]]

 [[ 8  7 10]
  [14 18 22]]]
[[[ 2  4  6  8]
  [ 1  3  5  7]
  [ 0  6  9 10]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [158]:
s=np.array([1,2,3,4])
ss=np.array([2,3,4,5])
np.square(s),np.power(s,ss)

(array([ 1,  4,  9, 16], dtype=int32),
 array([   1,    8,   81, 1024], dtype=int32))

In [182]:
np.greater(data1,data2)

array([[False, False,  True, False, False],
       [False, False,  True, False, False]])

In [188]:
print((data1>=10)|(data1<=5))

[ True  True  True  True  True]


In [187]:
data1

array([  1,   2, 100,   4,   5])

In [196]:
x=np.ones(3)
x

array([1., 1., 1.])

In [191]:
np.transpose(x,(1,0,2))

array([[[1., 1., 1.]],

       [[1., 1., 1.]]])

In [199]:
xx=np.array([1,2,3,4,5])
yy=np.array([6,7,8,9,0])
zz=np.array(["a","b","b","a","a"])
result=np.where(zz=="a",xx,yy)
print(result)

[1 7 8 4 5]


In [205]:
arr1=(70+30*np.random.randn(12).reshape(4,3))
arr2=(10+5*np.random.randn(12).reshape(4,3))
result=np.where(arr1>=60,arr1,np.where(arr2>=10,arr2,0))
print(result)

[[ 88.76709224   0.         103.76921405]
 [ 73.26341966  78.89417772   0.        ]
 [ 76.70403049  64.58755152  93.58932645]
 [ 20.01399564  12.61982469  96.17349696]]


In [209]:
result.argmax()

2

In [217]:
data2.mean(axis=1),data2.mean(axis=0),data2, data2.cumsum(axis=1),data2.var(axis=1),data2.std(axis=1)

(array([3., 8.]),
 array([3.5, 4.5, 5.5, 6.5, 7.5]),
 array([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]]),
 array([[ 1,  3,  6, 10, 15],
        [ 6, 13, 21, 30, 40]], dtype=int32),
 array([2., 2.]),
 array([1.41421356, 1.41421356]))

In [224]:
arr=np.array([True,True,True])
print(arr.all())

True


In [16]:
print(data2)
print(data2.transpose(0,1))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [13]:
data2.transpose(1,0)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [238]:
x=np.array([1,2,5,6,7,9,2,4])
y=np.array([8,2,6,7])
np.setxor1d(x,y), np.intersect1d(x,y),np.union1d(x,y),np.setdiff1d(y,x)

(array([1, 4, 5, 8, 9]),
 array([2, 6, 7]),
 array([1, 2, 4, 5, 6, 7, 8, 9]),
 array([8]))

In [240]:
(data2>=6).mean() # 전체 데이터 개수에서 6이상인 값의 개수 비율

0.5

In [5]:
A=np.arange(10)
B=np.arange(10,20,1)
np.save("C:/Users/Affinity/Desktop/수업/Python_Data/pp.npy","A")

In [17]:
steel_data=np.loadtxt("C:/Users/Affinity/Desktop/수업/Python_Data/ch02_data/steel.txt",skiprows=5,delimiter="\t")
print(steel_data)


[[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]]


In [20]:
steel_data=np.loadtxt("C:/Users/Affinity/Desktop/수업/Python_Data/ch02_data/steel.txt",skiprows=5,delimiter="\t",usecols=(0,1),unpack=True)
print(steel_data)

[[ 81.4 122.2 101.7 175.6 150.3  64.8  92.1 113.8]
 [195.  179.  205.  204.  201.  184.  210.  209. ]]


In [21]:
a=np.array([[1,3,5,7],[5,3,4,7]])
b=np.array([[1,3],[5,7],[5,3],[4,7]])
c=np.array([[4,9,1,3],[7,5,2,7],[5,3,4,3],[1,4,7,9]])



In [29]:
np.dot(a,b),np.diag(c)

(array([[69, 88],
        [68, 97]]), array([4, 5, 4, 9]))

In [26]:
np.diag(a[1])

array([[5, 0, 0, 0],
       [0, 3, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 7]])

In [28]:
np.trace(a)

4

In [30]:
np.linalg.det(c)

-1549.999999999999

In [39]:
cc=np.linalg.inv(c)

In [40]:
np.dot(c,cc)

array([[ 1.00000000e+00,  1.38777878e-16,  8.32667268e-17,
         5.55111512e-17],
       [-4.85722573e-17,  1.00000000e+00, -2.77555756e-17,
         1.66533454e-16],
       [-2.08166817e-17, -8.32667268e-17,  1.00000000e+00,
        -2.77555756e-17],
       [-2.28983499e-16,  1.38777878e-16, -1.94289029e-16,
         1.00000000e+00]])

In [42]:
np.linalg.eig(c) # 고유값, 고유행렬 순서로 출력

(array([18.95137965+0.j        , -4.18786225+0.j        ,
         3.6182413 +2.53735307j,  3.6182413 -2.53735307j]),
 array([[ 0.47831238+0.j        ,  0.64722509+0.j        ,
         -0.47647899-0.11511806j, -0.47647899+0.11511806j],
        [ 0.56955835+0.j        , -0.65592208+0.j        ,
         -0.12915359-0.16898385j, -0.12915359+0.16898385j],
        [ 0.38401956+0.j        , -0.26047634+0.j        ,
         -0.37310913+0.35580654j, -0.37310913-0.35580654j],
        [ 0.54712843+0.j        ,  0.2881284 +0.j        ,
          0.66982886+0.j        ,  0.66982886-0.j        ]]))

In [19]:
steel_data=np.loadtxt("C:/Users/Affinity/Desktop/수업/Python_Data/ch02_data/steel.txt",skiprows=5,delimiter="\t")

print(steel_data)

[[ 81.4 195.   57. ]
 [122.2 179.   61. ]
 [101.7 205.   60. ]
 [175.6 204.   62. ]
 [150.3 201.   61. ]
 [ 64.8 184.   54. ]
 [ 92.1 210.   58. ]
 [113.8 209.   61. ]]


In [27]:
y=steel_data[:,0].copy()
x=steel_data.copy()
x[:,0]=1
x,y

(array([[  1., 195.,  57.],
        [  1., 179.,  61.],
        [  1., 205.,  60.],
        [  1., 204.,  62.],
        [  1., 201.,  61.],
        [  1., 184.,  54.],
        [  1., 210.,  58.],
        [  1., 209.,  61.]]),
 array([ 81.4, 122.2, 101.7, 175.6, 150.3,  64.8,  92.1, 113.8]))

In [28]:
print(np.linalg.lstsq(x,y)) # 결과값 순서: 회귀계수 베타, sse, x의 랭크 수, x=UDV^T에서 D의 고유값의 제곱근

(array([-5.54311223e+02, -1.79739607e-01,  1.18599927e+01]), array([2340.88393765]), 3, array([5.86352311e+02, 8.94176555e+00, 1.09839713e-01]))


C:\ProgramData\Anaconda3\envs\jy3.6\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [32]:
sq= np.linalg.lstsq(x,y)[0]
new_X=(1,200,60)
print(sum(sq*new_X)) # 새로운 case의 값 (1,200,60)에 회귀식을 적용했을 때 종속변수 y 값

121.340417666711


C:\ProgramData\Anaconda3\envs\jy3.6\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  """Entry point for launching an IPython kernel.


In [41]:
np.dot(np.dot(np.linalg.inv(np.dot(x.T,x)),x.T),y)

array([-5.54311223e+02, -1.79739607e-01,  1.18599927e+01])

In [45]:
np.random.seed(11)
un=np.random.uniform(low=0,high=10,size=(3,4))
un

array([[1.80269689, 0.19475241, 4.63218526, 7.24933929],
       [4.20203605, 4.85427098, 0.12780815, 4.87371607],
       [9.41806652, 8.50795089, 7.2996447 , 1.08736072]])

In [72]:

nm=np.random.normal(loc=0,scale=2,size=10)
nm,np.mean(nm),np.var(nm)

(array([ 3.13967843,  3.04332702,  1.57983119, -0.43444179, -4.3681197 ,
        -3.13453682, -1.61934052,  1.00099021, -0.38701971, -1.3284064 ]),
 -0.2508038076535297,
 5.561948446423633)